#!/usr/bin/env bash
# Configure custom HTTP response header

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" >> /var/www/html/index.html
sudo sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart

