#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install haproxy=1.8.\* -y
sudo chmod 764 /etc/haproxy/
sudo chmod 764 /etc/haproxy/haproxy.cfg
sudo sed -i "$ a frontend Local_Server \n\t bind *:80 \n\t mode http \n\t default_backend My_Web_Servers \n\nbackend My_Web_Servers \n\t mode http \n\t balance roundrobin \n\t server 1515-web-01 3.91.197.132:80 check \n\t server 1515-web-02 34.74.87.14:80 check \n" /etc/haproxy/haproxy.cfg

sudo service haproxy restart

