#!/usr/bin/env bash
# Advanced 100

trap "sudo rm -f /var/run/holbertonscript.pid; exit 0"SIGQUIT
trap "echo I hate the kill command; sudo rm -f /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; exit" SIGINT
echo $$ > /var/run/holbertonscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done

